"""test migrate

Revision ID: e13fea70fc0c
Revises: 5a6cc35b9c27
Create Date: 2020-05-08 18:54:32.525517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e13fea70fc0c'
down_revision = '5a6cc35b9c27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cars', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cars', type_='unique')
    # ### end Alembic commands ###
